spring:
  application:
    name: user-manager
  datasource:
    url: jdbc:mysql://${db_host}:${db_port}/${db_name}
    username: ${db_user}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
